"""Evaluation script: compare raw LLM output vs MCRS pipeline output.

Workflow:
    1. Generate raw baseline manually (e.g. in a separate Claude Code session)
    2. Run the pipeline: python scripts/evaluate.py run "prompt" --type report
    3. Drop your raw baseline into the eval dir as raw_output.md
    4. Judge both:  python scripts/evaluate.py judge outputs/evals/<dir>/

The judge uses whatever LLM provider is configured in .env (OpenRouter, Anthropic, Ollama, etc).
"""

import argparse
import asyncio
import json
import random
import re
import sys
import time
from datetime import date, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
EVAL_DIR = PROJECT_ROOT / "outputs" / "evals"

JUDGE_RUBRIC = """\
You are an expert evaluator comparing two written artifacts generated from the same prompt.

## Your Task

Score both outputs on six dimensions. Each dimension is scored 1–5:
  1 = Poor, 2 = Below Average, 3 = Average, 4 = Good, 5 = Excellent

## Dimensions

1. **Structure & Organization** — Logical flow, clear headings, coherent narrative arc, appropriate use of sections.
2. **Research Depth & Evidence** — Specificity of claims, quality/diversity of evidence, data points, sourcing.
3. **Epistemic Rigor** — Appropriate hedging of uncertain claims, distinguishing fact from speculation, acknowledging limitations.
4. **Actionability** — Concrete recommendations, practical next steps, specific rather than vague guidance.
5. **Factual Accuracy** — Absence of hallucinations, verifiable claims, plausible data.
6. **Completeness** — Thorough coverage of the topic, no obvious gaps, appropriate depth.

## Instructions

- You will receive the original prompt and two outputs labeled "Output A" and "Output B".
- You do NOT know which output was generated by which method. Judge purely on quality.
- For each dimension, score BOTH outputs and provide 1-2 sentences of reasoning.
- After scoring all dimensions, declare an overall winner (A, B, or Tie) with a brief justification.

## Response Format

Respond with ONLY valid JSON matching this structure:

{
  "dimensions": {
    "structure": {"a": <int>, "b": <int>, "reasoning": "<string>"},
    "research_depth": {"a": <int>, "b": <int>, "reasoning": "<string>"},
    "epistemic_rigor": {"a": <int>, "b": <int>, "reasoning": "<string>"},
    "actionability": {"a": <int>, "b": <int>, "reasoning": "<string>"},
    "factual_accuracy": {"a": <int>, "b": <int>, "reasoning": "<string>"},
    "completeness": {"a": <int>, "b": <int>, "reasoning": "<string>"}
  },
  "overall_winner": "A" | "B" | "Tie",
  "overall_reasoning": "<string>",
  "a_total": <int>,
  "b_total": <int>
}
"""


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:50]


async def generate_pipeline_output(prompt: str, output_type: str) -> dict:
    """Run the MCRS pipeline and return the output + metadata."""
    from artifactforge.cli.main import _run_pipeline, select_output_content

    print(f"  Running MCRS pipeline ({output_type})...")
    start = time.monotonic()
    result = await _run_pipeline(prompt, output_type)
    duration_ms = (time.monotonic() - start) * 1000

    content = select_output_content(result) or ""
    tokens_used = result.get("tokens_used", {})
    costs = result.get("costs", {})

    print(
        f"  Done — {len(content)} chars, "
        f"{sum(tokens_used.values()) if isinstance(tokens_used, dict) else 0} total tokens, "
        f"{duration_ms / 1000:.1f}s"
    )
    return {
        "text": content,
        "tokens_used": tokens_used,
        "costs": costs,
        "duration_ms": round(duration_ms),
        "stages": result.get("stage_timing", {}),
        "errors": result.get("errors", []),
        "revision_count": len(result.get("revision_history", [])),
    }


async def run_judge(
    prompt: str,
    output_type: str,
    raw_text: str,
    pipeline_text: str,
) -> dict:
    """Run blind A/B comparison using the project's configured LLM provider."""
    from artifactforge.agents.llm_client import call_llm

    # Randomize assignment
    if random.random() < 0.5:
        a_text, b_text = raw_text, pipeline_text
        a_source, b_source = "raw", "pipeline"
    else:
        a_text, b_text = pipeline_text, raw_text
        a_source, b_source = "pipeline", "raw"

    user_prompt = f"""## Original Prompt
{prompt}

## Output Type
{output_type}

## Output A
{a_text}

## Output B
{b_text}
"""

    print(f"  Running blind judge...")
    start = time.monotonic()
    response_text = await call_llm(
        system_prompt=JUDGE_RUBRIC,
        user_prompt=user_prompt,
        temperature=0.0,
        max_tokens=4096,
    )
    duration_ms = (time.monotonic() - start) * 1000

    # Parse JSON from response
    text = response_text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)

    try:
        scores = json.loads(text)
    except json.JSONDecodeError:
        print(f"  Warning: Judge returned non-JSON. Saving raw response.")
        scores = {"raw_response": text, "parse_error": True}

    scores["assignment"] = {"a": a_source, "b": b_source}
    scores["judge_duration_ms"] = round(duration_ms)

    return scores


def build_judge_report(scores: dict, prompt: str, output_type: str) -> str:
    """Render judge scores as a readable markdown report."""
    lines = [
        "# Evaluation Judge Report",
        "",
        f"**Prompt:** {prompt[:200]}{'...' if len(prompt) > 200 else ''}",
        f"**Output Type:** {output_type}",
        f"**Assignment:** A = {scores['assignment']['a']}, B = {scores['assignment']['b']}",
        "",
    ]

    if scores.get("parse_error"):
        lines.append("## Raw Judge Response (JSON parse failed)")
        lines.append("")
        lines.append(scores.get("raw_response", ""))
        return "\n".join(lines)

    a_is = scores["assignment"]["a"]

    lines.append("## Scores (1-5 scale)")
    lines.append("")
    lines.append("| Dimension | Raw | Pipeline | Reasoning |")
    lines.append("|-----------|-----|----------|-----------|")

    dimensions = scores.get("dimensions", {})
    for dim_name, dim in dimensions.items():
        label = dim_name.replace("_", " ").title()
        a_score = dim.get("a", "?")
        b_score = dim.get("b", "?")
        reasoning = dim.get("reasoning", "").replace("|", "\\|")

        if a_is == "raw":
            raw_score, pipe_score = a_score, b_score
        else:
            raw_score, pipe_score = b_score, a_score

        lines.append(f"| {label} | {raw_score} | {pipe_score} | {reasoning} |")

    a_total = scores.get("a_total", "?")
    b_total = scores.get("b_total", "?")
    if a_is == "raw":
        raw_total, pipe_total = a_total, b_total
    else:
        raw_total, pipe_total = b_total, a_total
    lines.append(f"| **Total** | **{raw_total}** | **{pipe_total}** | |")

    winner_label = scores.get("overall_winner", "?")
    if winner_label in ("A", "B"):
        winner_source = scores["assignment"].get(winner_label.lower(), winner_label)
    else:
        winner_source = "Tie"

    lines.extend([
        "",
        f"## Overall Winner: **{winner_source.upper()}**",
        "",
        scores.get("overall_reasoning", ""),
    ])

    return "\n".join(lines)


def print_summary(scores: dict) -> None:
    """Print a compact terminal summary."""
    if scores.get("parse_error"):
        print("\n  Judge response could not be parsed as JSON.")
        return

    a_is = scores["assignment"]["a"]
    dims = scores.get("dimensions", {})

    print("\n  ┌─────────────────────┬───────┬──────────┐")
    print("  │ Dimension           │  Raw  │ Pipeline │")
    print("  ├─────────────────────┼───────┼──────────┤")

    for dim_name, dim in dims.items():
        label = dim_name.replace("_", " ").title()[:19]
        a_score = dim.get("a", 0)
        b_score = dim.get("b", 0)
        if a_is == "raw":
            raw_s, pipe_s = a_score, b_score
        else:
            raw_s, pipe_s = b_score, a_score
        print(f"  │ {label:<19} │   {raw_s}   │    {pipe_s}     │")

    print("  ├─────────────────────┼───────┼──────────┤")

    a_total = scores.get("a_total", 0)
    b_total = scores.get("b_total", 0)
    if a_is == "raw":
        raw_t, pipe_t = a_total, b_total
    else:
        raw_t, pipe_t = b_total, a_total
    print(f"  │ {'Total':<19} │  {raw_t:>2}   │   {pipe_t:>2}     │")
    print("  └─────────────────────┴───────┴──────────┘")

    winner_label = scores.get("overall_winner", "?")
    if winner_label in ("A", "B"):
        winner = scores["assignment"].get(winner_label.lower(), winner_label).upper()
    else:
        winner = "TIE"
    print(f"\n  Winner: {winner}")
    print(f"  {scores.get('overall_reasoning', '')}")


async def cmd_run(args: argparse.Namespace) -> None:
    """Run mode: run the pipeline and set up the eval directory."""
    prompt = args.prompt
    output_type = args.type

    # Create eval directory
    today = date.today().strftime("%Y-%m-%d")
    slug = slugify(prompt)
    eval_name = f"{today}-{slug}"
    eval_path = EVAL_DIR / eval_name
    eval_path.mkdir(parents=True, exist_ok=True)

    print(f"\nEval dir: {eval_path}\n")

    # Run pipeline
    print("[1/1] Running MCRS pipeline...")
    pipeline_result = await generate_pipeline_output(prompt, output_type)
    (eval_path / "pipeline_output.md").write_text(
        pipeline_result["text"], encoding="utf-8",
    )

    # Save metadata
    metadata = {
        "prompt": prompt,
        "output_type": output_type,
        "created_at": datetime.now().isoformat(),
        "pipeline": {
            "duration_ms": pipeline_result["duration_ms"],
            "char_count": len(pipeline_result["text"]),
            "tokens_used": pipeline_result["tokens_used"],
            "costs": pipeline_result["costs"],
            "stages": pipeline_result["stages"],
            "errors": pipeline_result["errors"],
            "revision_count": pipeline_result["revision_count"],
        },
    }
    (eval_path / "metadata.json").write_text(
        json.dumps(metadata, indent=2, default=str), encoding="utf-8",
    )

    print(f"\n  Pipeline output saved to: {eval_path / 'pipeline_output.md'}")
    print(f"\n  Next steps:")
    print(f"    1. Save your raw LLM baseline as: {eval_path / 'raw_output.md'}")
    print(f"    2. Run: python scripts/evaluate.py judge {eval_path}")


async def cmd_judge(args: argparse.Namespace) -> None:
    """Judge mode: blind A/B comparison of raw vs pipeline outputs."""
    eval_path = Path(args.eval_dir).resolve()

    if not eval_path.is_dir():
        print(f"Error: {eval_path} is not a directory")
        sys.exit(1)

    raw_path = eval_path / "raw_output.md"
    pipeline_path = eval_path / "pipeline_output.md"
    meta_path = eval_path / "metadata.json"

    if not raw_path.exists():
        print(f"Error: Missing {raw_path}")
        print(f"  Save your raw LLM baseline there first.")
        sys.exit(1)
    if not pipeline_path.exists():
        print(f"Error: Missing {pipeline_path}")
        sys.exit(1)

    raw_text = raw_path.read_text(encoding="utf-8")
    pipeline_text = pipeline_path.read_text(encoding="utf-8")

    # Load prompt from metadata
    if meta_path.exists():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        prompt = meta.get("prompt", "")
        output_type = meta.get("output_type", "report")
    else:
        print("Warning: No metadata.json found. Using empty prompt context.")
        prompt = ""
        output_type = "report"

    print(f"\nJudging: {eval_path}\n")
    print(f"  Raw: {len(raw_text):,} chars")
    print(f"  Pipeline: {len(pipeline_text):,} chars\n")

    scores = await run_judge(prompt, output_type, raw_text, pipeline_text)

    report = build_judge_report(scores, prompt, output_type)
    (eval_path / "judge_report.md").write_text(report, encoding="utf-8")

    # Update metadata
    if meta_path.exists():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    else:
        meta = {"prompt": prompt, "output_type": output_type}
    meta["judge"] = {"scores": scores}
    meta["judged_at"] = datetime.now().isoformat()
    meta_path.write_text(
        json.dumps(meta, indent=2, default=str), encoding="utf-8",
    )

    print_summary(scores)
    print(f"\n  Report saved to: {eval_path / 'judge_report.md'}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate MCRS pipeline vs raw LLM output",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # --- run ---
    run_parser = subparsers.add_parser(
        "run", help="Run the MCRS pipeline and set up eval directory",
    )
    run_parser.add_argument("prompt", help="The prompt to evaluate")
    run_parser.add_argument(
        "--type", "-t", default="report",
        help="Output type: report, blog, memo, technical_writeup, decision_doc, slides",
    )

    # --- judge ---
    judge_parser = subparsers.add_parser(
        "judge", help="Blind A/B comparison of raw vs pipeline outputs",
    )
    judge_parser.add_argument("eval_dir", help="Path to eval directory")

    args = parser.parse_args()

    if args.command == "run":
        asyncio.run(cmd_run(args))
    elif args.command == "judge":
        asyncio.run(cmd_judge(args))


if __name__ == "__main__":
    main()
